### ISSUE TITLE
load instance to either create meta data for it or clean and refill it

### ISSUE THREAD

**Issue by J-Behrens** [krr-up/mapf-instance-generator#29]
- [x] load an instance with or without agents, starts and goals and:
  - [x] just create meta data for instance
or 
  - [x] clean and refill instance with agents
